[package]
name = "af-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
af-runtime = { path = "../af-runtime" }
rocket = { version = "0.5", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

