[package]
name = "af-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
af-core = { path = "../af-core" }
af-ops = { path = "../af-ops" }
af-tokenizer = { path = "../af-tokenizer" }

